# Generated by Django 4.0.4 on 2022-04-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_delete_propaganda_remove_consultor_faculdade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultor',
            options={'verbose_name': 'Consultor', 'verbose_name_plural': 'Consultores'},
        ),
        migrations.AlterModelOptions(
            name='dieta',
            options={'verbose_name': 'Dieta', 'verbose_name_plural': 'Dietas'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Página incial'},
        ),
        migrations.AlterModelOptions(
            name='profissao',
            options={'verbose_name': 'Profissão', 'verbose_name_plural': 'Profissões'},
        ),
        migrations.AlterModelOptions(
            name='suplementacao',
            options={'verbose_name': 'Suplementação', 'verbose_name_plural': 'Suplementações'},
        ),
        migrations.AlterModelOptions(
            name='treinos',
            options={'verbose_name': 'Treino', 'verbose_name_plural': 'Treinos'},
        ),
        migrations.AddField(
            model_name='consultor',
            name='preco',
            field=models.FloatField(default=0),
        ),
    ]
