# Generated by Django 4.0.4 on 2022-04-28 20:49

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_suplementacao_link_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suplementacao',
            name='link_propaganda',
        ),
        migrations.AlterField(
            model_name='suplementacao',
            name='link_imagem',
            field=stdimage.models.StdImageField(blank=True, upload_to='suplementacao', verbose_name='Imagem_link'),
        ),
    ]
